export type AppAccessibilityRole =
  | 'none'
  | 'button'
  | 'link'
  | 'search'
  | 'image'
  | 'keyboardkey'
  | 'text'
  | 'adjustable'
  | 'header'
  | 'summary'
  | 'imagebutton'
  | 'heading'
  | 'navigation'
  | 'main'
  | 'article'
  | 'list'
  | 'listitem'
